### ISSUE TITLE
Question about custom crawls on startServer functionality

### ISSUE THREAD

**Issue by pariskoloveas** [VIDA-NYU/ache#178]
Is there a way to define specifically configured crawls while running ache on server mode?
I am using a docker compose file which is structured as my docker-compose file with the startCrawl command but when I look into the data-ache folder, the config folder that has been created has the default ache.yml and no link-filters.yml file.

```yml
version: '2'
services:
  ache:
    image: vidanyu/ache
    entrypoint: sh -c 'sleep 10 && /ache/bin/ache startServer -d /data' -c /config/ 
    ports:
      - "8080:8080"
    volumes:
      - ./data-ache/:/data
      - ./:/config
```

Also, after the server is up, and I can create new crawls from the interface, how can I specify that for example, a new focused crawl has a different ache.yml file for the configuration without restarting the docker container?
