### ISSUE TITLE
New regex-based page classifier that matches multiple fields simultaneously

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#69]
Currently, there are 3 types of regex based classifiers based on fields `URL`, `content`, and `title`. But there is no way to match all fields at the same time, or combine multiple classifiers.

It would be useful a regex classifier can boolean combination (OR or AND) of regexes in multiple fields:

```yaml
type: regex
parameters:
  combiner: OR|AND
  fields:
    url:
    - pattern1-for-url
    - pattern2-for-url
    title:
    - pattern1-for-title
    content:
    - pattern1-for-content
```

**Comment by aecio** [comment]
A more flexible alternative would be like this:

```yaml
type: regex
parameters:
    boolean_operator: "[AND|OR]"
    url:
      boolean_operator: "[AND|OR]"
      regexes:
        - pattern1-for-url
        - pattern2-for-url
    title:
      boolean_operator: "[AND|OR]"
      regexes:
        - pattern1-for-title
        - pattern2-for-title
    content:    
      boolean_operator: "[AND|OR]"
      regexes:
        - pattern1-for-content
```
The first level `boolean_operator` would define how to combine the results of each field, and the `boolean_operator` in the second level would define how to combine each regex for that specific field.

@1130695 Bruno, would this work better for you?

**Comment by 1130695** [comment]
Yes, I think that something like this would be a possible result to my current issue, being capable of adding the 3 regex in 1 classifier would be lovely.

I still have 2 questions if you don't mind me:

- Would it be possible to make the classifier/regex only set a certain page as relevant if it passes on all the given patterns for each type of parameter?
For example, for a page's url to be classified as relevant, it would have to pass both pattern 1 and 2 and not only one of them.

- Lastly, could you give me a short example on how you'd apply those boolean operators? I assume they're not the same as their regex parts ( '|', '?=').

**Comment by aecio** [comment]
These boolean operators  would serve exactly for that purpose. If you choose AND, all regexes need to match in order to the page be classified as relevant. If you choose OR, only one of the regexes would be required to match.

For example, consider the following setting:

```yaml
type: regex
parameters:
    boolean_operator: "AND"
    url:
      boolean_operator: "AND"
      regexes:
        - .*category=1.*
        - .*post\.php.*
    title:
      boolean_operator: "OR"
      regexes:
        - .*bar.*
        - .*foo.*
```

To be classified as relevant, a page would need to:
-  match regexes `.*category=1.*` AND `.*post\.php.*` in the URL
- AND
- it would have to match `.*bar.*` OR `.*foo.*` in the Title.

@1130695, is it clear now?
