### ISSUE TITLE
Creation of a Classifier that would have both WEKA and regex-based classifier in consideration

### ISSUE THREAD

**Issue by 1130695** [ViDA-NYU/ache#77]
Title. It would be pretty sweet if we could build a Classifier that would classify a certain page using regex and WEKA.  This would help us getting a more precise output. 

We could start off by building one with the "baseline" behaviour and adapt it from there.

@aecio , you said this was somewhat easy to do, but I don't know very well how the weka classification options you have available work exactly. Which ones would work better together? Authority with BS?

**Comment by aecio** [comment]
Are we talking about a new link classifier? I assumed it was a target page classifier.

**Comment by 1130695** [comment]
My bad, We're talking about a new target page classifier, was kinda sleepy -.- Forget about the link classification example.

**Comment by aecio** [comment]
I was thinking in having a more generic classifier that can combine a list of any other existing classifier. For example, it would be configured like this:
```yaml
type: combiner
parameters:
  boolean_operator: OR
  classifiers:
    - type: url_regex
      parameters:
        regular_expressions: [
          "https?://www\\.somedomain\\.com/forum/.*"
          ".*/thread/.*",
          ".*/archive/index.php/t.*",
        ]
    - type: weka
      parameters:
        features_file: pageclassifier.features
        model_file: pageclassifier.model
```

The key `classifiers` could be a list of any target page classifier available along with its parameters.

**Comment by julianafreire** [comment]
I like the idea. This would be very useful.
Are you planning to support complex boolean expressions? Or just "OR" and just "AND"?

**Comment by aecio** [comment]
What do you mean by complex boolean expresions? Could you give an example?

**Comment by julianafreire** [comment]
E.g., (A AND B) OR (C AND D)

I think we can start with just simple queries A AND B AND C ..., or A OR B OR C... 
This would already be very useful.

**Comment by 1130695** [comment]
Yup, this would do the trick @aecio ! Adding this format means that the one you made a month ago wouldn't be necessary anymore since this one would have  everything in consideration

Regarding the situation of @julianafreire  , I think @aecio  already implemented it if you check the regex he made a while back. And I'm not sure, but I think you can apply it in this scenario as well.


For example url_regex (parameter_1 OR parameter_2) AND body_regex (parameter_1 AND parameter_2 AND parameter_3) OR weka (...)

**Comment by 1130695** [comment]
https://github.com/ViDA-NYU/ache/issues/69

**Comment by aecio** [comment]
Got it. I think nesting `combiner` classifiers would enable complex boolean expressions and could be easily supported. It would also enable combination of weka models with arbitrary regex-based classifiers. For example:

```yaml
type: combiner
parameters:
  boolean_operator: OR
  classifiers:
    - type: combiner
      parameters:
        boolean_operator: AND
        classifiers: 
          - type: url_regex
            parameters:
              regular_expressions: ["https?://www\\.somedomain\\.com/forum/.*"]
          - type: weka
            parameters:
              features_file: model_01/pageclassifier.features
              model_file: model_01/pageclassifier.model
    - type: weka
      parameters:
        features_file: model_02/pageclassifier.features
        model_file: model_02/pageclassifier.model
```
